# Configure in which directory your code is located.
# This can be set to any subdirectory of your project.
working_directory: sf-api
global_exclude_dirs:
  - vendor
  - node_modules
  - public/build
